
/*
 * Created on 17 May 2016 ( Time 04:14:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.mock;

import java.util.LinkedList;
import java.util.List;

import org.marks.bean.jpa.DisciplineParamsEntity;
import org.marks.mock.tool.MockValues;

public class DisciplineParamsEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public DisciplineParamsEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public DisciplineParamsEntity createInstance( Integer id ) {
		DisciplineParamsEntity entity = new DisciplineParamsEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setActivityName( mockValues.nextString(2147483647) ) ; // java.lang.String 
		entity.setActivityMaxQuantity( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setScorePerActivity( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setScoreMax( mockValues.nextInteger() ) ; // java.lang.Integer 
		// Init Link fields (if any)
		// setDisciplinesSemestr( TODO ) ; // DisciplinesSemestr 
		// setListOfStudentsDisciplineSemestr( TODO ) ; // List<StudentsDisciplineSemestr> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<DisciplineParamsEntity> createList(int count) {
		List<DisciplineParamsEntity> list = new LinkedList<DisciplineParamsEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
