
/*
 * Created on 17 May 2016 ( Time 04:14:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.mock;

import java.util.LinkedList;
import java.util.List;

import org.marks.bean.jpa.DisciplinesEntity;
import org.marks.mock.tool.MockValues;

public class DisciplinesEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public DisciplinesEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public DisciplinesEntity createInstance( Integer id ) {
		DisciplinesEntity entity = new DisciplinesEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setName( mockValues.nextString(2147483647) ) ; // java.lang.String 
		entity.setStudyPlanCode( mockValues.nextInteger() ) ; // java.lang.Integer 
		// Init Link fields (if any)
		// setTeachers( TODO ) ; // Teachers 
		// setListOfDisciplinesSemestr( TODO ) ; // List<DisciplinesSemestr> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<DisciplinesEntity> createList(int count) {
		List<DisciplinesEntity> list = new LinkedList<DisciplinesEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
