
/*
 * Created on 17 May 2016 ( Time 04:14:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.mock;

import java.util.LinkedList;
import java.util.List;

import org.marks.bean.jpa.GroupsEntity;
import org.marks.mock.tool.MockValues;

public class GroupsEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public GroupsEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public GroupsEntity createInstance( Integer id ) {
		GroupsEntity entity = new GroupsEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setCourse( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setGroupNumber( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setFaculty( mockValues.nextString(80) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setSpecialities( TODO ) ; // Specialities 
		// setListOfStudents( TODO ) ; // List<Students> 
		// setSpecialities2( TODO ) ; // Specialities 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<GroupsEntity> createList(int count) {
		List<GroupsEntity> list = new LinkedList<GroupsEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
