
/*
 * Created on 17 May 2016 ( Time 04:14:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.mock;

import java.util.LinkedList;
import java.util.List;

import org.marks.bean.jpa.TeachersEntity;
import org.marks.mock.tool.MockValues;

public class TeachersEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public TeachersEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public TeachersEntity createInstance( Integer id ) {
		TeachersEntity entity = new TeachersEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setFullName( mockValues.nextString(2147483647) ) ; // java.lang.String 
		entity.setLogin( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setPassword( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setCathedra( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setEnabled( mockValues.nextString(2147483647) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfDisciplines( TODO ) ; // List<Disciplines> 
		// setRoles( TODO ) ; // Roles 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<TeachersEntity> createList(int count) {
		List<TeachersEntity> list = new LinkedList<TeachersEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
