/*
 * Created on 17 May 2016 ( Time 04:14:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.marks.bean.jpa.DisciplinesEntity;
import org.marks.persistence.commons.fake.GenericFakeService;
import org.marks.persistence.services.DisciplinesPersistence;

/**
 * Fake persistence service implementation ( entity "Disciplines" )
 *
 * @author Telosys Tools Generator
 */
public class DisciplinesPersistenceFAKE extends GenericFakeService<DisciplinesEntity> implements DisciplinesPersistence {

	public DisciplinesPersistenceFAKE () {
		super(DisciplinesEntity.class);
	}
	
	protected DisciplinesEntity buildEntity(int index) {
		DisciplinesEntity entity = new DisciplinesEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setName( nextString() ) ;
		entity.setStudyPlanCode( nextInteger() ) ;
		return entity ;
	}
	
	
	public boolean delete(DisciplinesEntity entity) {
		log("delete ( DisciplinesEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(DisciplinesEntity entity) {
		log("insert ( DisciplinesEntity : " + entity + ")" ) ;
	}

	public DisciplinesEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<DisciplinesEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<DisciplinesEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<DisciplinesEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public DisciplinesEntity save(DisciplinesEntity entity) {
		log("insert ( DisciplinesEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<DisciplinesEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
