/*
 * Created on 17 May 2016 ( Time 04:14:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.marks.bean.jpa.DisciplineParamsEntity;
import org.marks.persistence.commons.fake.GenericFakeService;
import org.marks.persistence.services.DisciplineParamsPersistence;

/**
 * Fake persistence service implementation ( entity "DisciplineParams" )
 *
 * @author Telosys Tools Generator
 */
public class DisciplineParamsPersistenceFAKE extends GenericFakeService<DisciplineParamsEntity> implements DisciplineParamsPersistence {

	public DisciplineParamsPersistenceFAKE () {
		super(DisciplineParamsEntity.class);
	}
	
	protected DisciplineParamsEntity buildEntity(int index) {
		DisciplineParamsEntity entity = new DisciplineParamsEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setActivityName( nextString() ) ;
		entity.setActivityMaxQuantity( nextInteger() ) ;
		entity.setScorePerActivity( nextInteger() ) ;
		entity.setScoreMax( nextInteger() ) ;
		return entity ;
	}
	
	
	public boolean delete(DisciplineParamsEntity entity) {
		log("delete ( DisciplineParamsEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(DisciplineParamsEntity entity) {
		log("insert ( DisciplineParamsEntity : " + entity + ")" ) ;
	}

	public DisciplineParamsEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<DisciplineParamsEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<DisciplineParamsEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<DisciplineParamsEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public DisciplineParamsEntity save(DisciplineParamsEntity entity) {
		log("insert ( DisciplineParamsEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<DisciplineParamsEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
