/*
 * Created on 17 May 2016 ( Time 04:14:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.marks.bean.jpa.DisciplinesSemestrEntity;
import org.marks.persistence.commons.fake.GenericFakeService;
import org.marks.persistence.services.DisciplinesSemestrPersistence;

/**
 * Fake persistence service implementation ( entity "DisciplinesSemestr" )
 *
 * @author Telosys Tools Generator
 */
public class DisciplinesSemestrPersistenceFAKE extends GenericFakeService<DisciplinesSemestrEntity> implements DisciplinesSemestrPersistence {

	public DisciplinesSemestrPersistenceFAKE () {
		super(DisciplinesSemestrEntity.class);
	}
	
	protected DisciplinesSemestrEntity buildEntity(int index) {
		DisciplinesSemestrEntity entity = new DisciplinesSemestrEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setSemestr( nextInteger() ) ;
		return entity ;
	}
	
	
	public boolean delete(DisciplinesSemestrEntity entity) {
		log("delete ( DisciplinesSemestrEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(DisciplinesSemestrEntity entity) {
		log("insert ( DisciplinesSemestrEntity : " + entity + ")" ) ;
	}

	public DisciplinesSemestrEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<DisciplinesSemestrEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<DisciplinesSemestrEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<DisciplinesSemestrEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public DisciplinesSemestrEntity save(DisciplinesSemestrEntity entity) {
		log("insert ( DisciplinesSemestrEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<DisciplinesSemestrEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
