/*
 * Created on 17 May 2016 ( Time 04:14:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.marks.bean.jpa.RolesEntity;
import org.marks.persistence.commons.fake.GenericFakeService;
import org.marks.persistence.services.RolesPersistence;

/**
 * Fake persistence service implementation ( entity "Roles" )
 *
 * @author Telosys Tools Generator
 */
public class RolesPersistenceFAKE extends GenericFakeService<RolesEntity> implements RolesPersistence {

	public RolesPersistenceFAKE () {
		super(RolesEntity.class);
	}
	
	protected RolesEntity buildEntity(int index) {
		RolesEntity entity = new RolesEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setRoleName( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(RolesEntity entity) {
		log("delete ( RolesEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(RolesEntity entity) {
		log("insert ( RolesEntity : " + entity + ")" ) ;
	}

	public RolesEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<RolesEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<RolesEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<RolesEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public RolesEntity save(RolesEntity entity) {
		log("insert ( RolesEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<RolesEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
