/*
 * Created on 17 May 2016 ( Time 04:14:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.marks.bean.jpa.SpecialitiesEntity;
import org.marks.persistence.commons.fake.GenericFakeService;
import org.marks.persistence.services.SpecialitiesPersistence;

/**
 * Fake persistence service implementation ( entity "Specialities" )
 *
 * @author Telosys Tools Generator
 */
public class SpecialitiesPersistenceFAKE extends GenericFakeService<SpecialitiesEntity> implements SpecialitiesPersistence {

	public SpecialitiesPersistenceFAKE () {
		super(SpecialitiesEntity.class);
	}
	
	protected SpecialitiesEntity buildEntity(int index) {
		SpecialitiesEntity entity = new SpecialitiesEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setSpecialityName( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(SpecialitiesEntity entity) {
		log("delete ( SpecialitiesEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(SpecialitiesEntity entity) {
		log("insert ( SpecialitiesEntity : " + entity + ")" ) ;
	}

	public SpecialitiesEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<SpecialitiesEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<SpecialitiesEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<SpecialitiesEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public SpecialitiesEntity save(SpecialitiesEntity entity) {
		log("insert ( SpecialitiesEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<SpecialitiesEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
