/*
 * Created on 17 May 2016 ( Time 04:14:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.marks.bean.jpa.StudentsEntity;
import org.marks.persistence.commons.fake.GenericFakeService;
import org.marks.persistence.services.StudentsPersistence;

/**
 * Fake persistence service implementation ( entity "Students" )
 *
 * @author Telosys Tools Generator
 */
public class StudentsPersistenceFAKE extends GenericFakeService<StudentsEntity> implements StudentsPersistence {

	public StudentsPersistenceFAKE () {
		super(StudentsEntity.class);
	}
	
	protected StudentsEntity buildEntity(int index) {
		StudentsEntity entity = new StudentsEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setFullName( nextString() ) ;
		entity.setRecordBookNumber( nextInteger() ) ;
		entity.setStartYear( nextDate() ) ;
		entity.setEndYear( nextDate() ) ;
		return entity ;
	}
	
	
	public boolean delete(StudentsEntity entity) {
		log("delete ( StudentsEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(StudentsEntity entity) {
		log("insert ( StudentsEntity : " + entity + ")" ) ;
	}

	public StudentsEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<StudentsEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<StudentsEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<StudentsEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public StudentsEntity save(StudentsEntity entity) {
		log("insert ( StudentsEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<StudentsEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
