/*
 * Created on 17 May 2016 ( Time 04:14:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.marks.bean.jpa.StudentsDisciplineSemestrEntity;
import org.marks.persistence.commons.fake.GenericFakeService;
import org.marks.persistence.services.StudentsDisciplineSemestrPersistence;

/**
 * Fake persistence service implementation ( entity "StudentsDisciplineSemestr" )
 *
 * @author Telosys Tools Generator
 */
public class StudentsDisciplineSemestrPersistenceFAKE extends GenericFakeService<StudentsDisciplineSemestrEntity> implements StudentsDisciplineSemestrPersistence {

	public StudentsDisciplineSemestrPersistenceFAKE () {
		super(StudentsDisciplineSemestrEntity.class);
	}
	
	protected StudentsDisciplineSemestrEntity buildEntity(int index) {
		StudentsDisciplineSemestrEntity entity = new StudentsDisciplineSemestrEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setStudentScore( nextInteger() ) ;
		return entity ;
	}
	
	
	public boolean delete(StudentsDisciplineSemestrEntity entity) {
		log("delete ( StudentsDisciplineSemestrEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(StudentsDisciplineSemestrEntity entity) {
		log("insert ( StudentsDisciplineSemestrEntity : " + entity + ")" ) ;
	}

	public StudentsDisciplineSemestrEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<StudentsDisciplineSemestrEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<StudentsDisciplineSemestrEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<StudentsDisciplineSemestrEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public StudentsDisciplineSemestrEntity save(StudentsDisciplineSemestrEntity entity) {
		log("insert ( StudentsDisciplineSemestrEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<StudentsDisciplineSemestrEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
