/*
 * Created on 17 May 2016 ( Time 04:14:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.marks.bean.jpa.TeachersEntity;
import org.marks.persistence.commons.fake.GenericFakeService;
import org.marks.persistence.services.TeachersPersistence;

/**
 * Fake persistence service implementation ( entity "Teachers" )
 *
 * @author Telosys Tools Generator
 */
public class TeachersPersistenceFAKE extends GenericFakeService<TeachersEntity> implements TeachersPersistence {

	public TeachersPersistenceFAKE () {
		super(TeachersEntity.class);
	}
	
	protected TeachersEntity buildEntity(int index) {
		TeachersEntity entity = new TeachersEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setFullName( nextString() ) ;
		entity.setLogin( nextString() ) ;
		entity.setPassword( nextString() ) ;
		entity.setCathedra( nextString() ) ;
		entity.setEnabled( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(TeachersEntity entity) {
		log("delete ( TeachersEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(TeachersEntity entity) {
		log("insert ( TeachersEntity : " + entity + ")" ) ;
	}

	public TeachersEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<TeachersEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<TeachersEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<TeachersEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public TeachersEntity save(TeachersEntity entity) {
		log("insert ( TeachersEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<TeachersEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
