/*
 * Created on 17 May 2016 ( Time 04:14:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.test.persistence;


import org.marks.bean.jpa.SpecialitiesEntity;
import org.marks.mock.SpecialitiesEntityMock;
import org.marks.persistence.PersistenceServiceProvider;
import org.marks.persistence.services.SpecialitiesPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Specialities persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class SpecialitiesPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		SpecialitiesPersistence service = PersistenceServiceProvider.getService(SpecialitiesPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Specialities persistence : delete + load ..." );
		
		SpecialitiesPersistence service = PersistenceServiceProvider.getService(SpecialitiesPersistence.class);
		
		SpecialitiesEntityMock mock = new SpecialitiesEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(SpecialitiesPersistence service, SpecialitiesEntityMock mock, Integer id ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		SpecialitiesEntity entity = service.load( id );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( id ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( id );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
