/*
 * Created on 17 May 2016 ( Time 04:14:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.marks.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import org.marks.bean.jpa.StudentsDisciplineSemestrEntity;
import org.marks.persistence.commons.jpa.GenericJpaService;
import org.marks.persistence.commons.jpa.JpaOperation;
import org.marks.persistence.services.StudentsDisciplineSemestrPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "StudentsDisciplineSemestr" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class StudentsDisciplineSemestrPersistenceJPA extends GenericJpaService<StudentsDisciplineSemestrEntity, Integer> implements StudentsDisciplineSemestrPersistence {

	/**
	 * Constructor
	 */
	public StudentsDisciplineSemestrPersistenceJPA() {
		super(StudentsDisciplineSemestrEntity.class);
	}

	@Override
	public StudentsDisciplineSemestrEntity load( Integer id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Integer id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(StudentsDisciplineSemestrEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("StudentsDisciplineSemestrEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
