/*
 * Created on 17 May 2016 ( Time 04:14:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.web.listitem;

import org.marks.bean.DisciplinesSemestr;
import org.marks.web.common.ListItem;

public class DisciplinesSemestrListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public DisciplinesSemestrListItem(DisciplinesSemestr disciplinesSemestr) {
		super();

		this.value = ""
			 + disciplinesSemestr.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = disciplinesSemestr.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
