/*
 * Created on 17 May 2016 ( Time 04:14:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.marks.bean.DisciplineParams;
import org.marks.bean.jpa.DisciplineParamsEntity;
import org.marks.bean.jpa.DisciplinesSemestrEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class DisciplineParamsServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public DisciplineParamsServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'DisciplineParamsEntity' to 'DisciplineParams'
	 * @param disciplineParamsEntity
	 */
	public DisciplineParams mapDisciplineParamsEntityToDisciplineParams(DisciplineParamsEntity disciplineParamsEntity) {
		if(disciplineParamsEntity == null) {
			return null;
		}

		//--- Generic mapping 
		DisciplineParams disciplineParams = map(disciplineParamsEntity, DisciplineParams.class);

		//--- Link mapping ( link to DisciplinesSemestr )
		if(disciplineParamsEntity.getDisciplinesSemestr() != null) {
			disciplineParams.setDisciplineSemestrId(disciplineParamsEntity.getDisciplinesSemestr().getId());
		}
		return disciplineParams;
	}
	
	/**
	 * Mapping from 'DisciplineParams' to 'DisciplineParamsEntity'
	 * @param disciplineParams
	 * @param disciplineParamsEntity
	 */
	public void mapDisciplineParamsToDisciplineParamsEntity(DisciplineParams disciplineParams, DisciplineParamsEntity disciplineParamsEntity) {
		if(disciplineParams == null) {
			return;
		}

		//--- Generic mapping 
		map(disciplineParams, disciplineParamsEntity);

		//--- Link mapping ( link : disciplineParams )
		if( hasLinkToDisciplinesSemestr(disciplineParams) ) {
			DisciplinesSemestrEntity disciplinesSemestr1 = new DisciplinesSemestrEntity();
			disciplinesSemestr1.setId( disciplineParams.getDisciplineSemestrId() );
			disciplineParamsEntity.setDisciplinesSemestr( disciplinesSemestr1 );
		} else {
			disciplineParamsEntity.setDisciplinesSemestr( null );
		}

	}
	
	/**
	 * Verify that DisciplinesSemestr id is valid.
	 * @param DisciplinesSemestr DisciplinesSemestr
	 * @return boolean
	 */
	private boolean hasLinkToDisciplinesSemestr(DisciplineParams disciplineParams) {
		if(disciplineParams.getDisciplineSemestrId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}