/*
 * Created on 17 May 2016 ( Time 04:14:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.marks.bean.Specialities;
import org.marks.bean.jpa.SpecialitiesEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class SpecialitiesServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public SpecialitiesServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'SpecialitiesEntity' to 'Specialities'
	 * @param specialitiesEntity
	 */
	public Specialities mapSpecialitiesEntityToSpecialities(SpecialitiesEntity specialitiesEntity) {
		if(specialitiesEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Specialities specialities = map(specialitiesEntity, Specialities.class);

		return specialities;
	}
	
	/**
	 * Mapping from 'Specialities' to 'SpecialitiesEntity'
	 * @param specialities
	 * @param specialitiesEntity
	 */
	public void mapSpecialitiesToSpecialitiesEntity(Specialities specialities, SpecialitiesEntity specialitiesEntity) {
		if(specialities == null) {
			return;
		}

		//--- Generic mapping 
		map(specialities, specialitiesEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}