/*
 * Created on 17 May 2016 ( Time 04:14:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.marks.bean.Students;
import org.marks.bean.jpa.StudentsEntity;
import org.marks.bean.jpa.GroupsEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class StudentsServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public StudentsServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'StudentsEntity' to 'Students'
	 * @param studentsEntity
	 */
	public Students mapStudentsEntityToStudents(StudentsEntity studentsEntity) {
		if(studentsEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Students students = map(studentsEntity, Students.class);

		//--- Link mapping ( link to Groups )
		if(studentsEntity.getGroups() != null) {
			students.setGroupId(studentsEntity.getGroups().getId());
		}
		return students;
	}
	
	/**
	 * Mapping from 'Students' to 'StudentsEntity'
	 * @param students
	 * @param studentsEntity
	 */
	public void mapStudentsToStudentsEntity(Students students, StudentsEntity studentsEntity) {
		if(students == null) {
			return;
		}

		//--- Generic mapping 
		map(students, studentsEntity);

		//--- Link mapping ( link : students )
		if( hasLinkToGroups(students) ) {
			GroupsEntity groups1 = new GroupsEntity();
			groups1.setId( students.getGroupId() );
			studentsEntity.setGroups( groups1 );
		} else {
			studentsEntity.setGroups( null );
		}

	}
	
	/**
	 * Verify that Groups id is valid.
	 * @param Groups Groups
	 * @return boolean
	 */
	private boolean hasLinkToGroups(Students students) {
		if(students.getGroupId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}