/*
 * Created on 17 May 2016 ( Time 04:14:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.marks.bean.Teachers;
import org.marks.bean.jpa.TeachersEntity;
import org.marks.bean.jpa.RolesEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TeachersServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public TeachersServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TeachersEntity' to 'Teachers'
	 * @param teachersEntity
	 */
	public Teachers mapTeachersEntityToTeachers(TeachersEntity teachersEntity) {
		if(teachersEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Teachers teachers = map(teachersEntity, Teachers.class);

		//--- Link mapping ( link to Roles )
		if(teachersEntity.getRoles() != null) {
			teachers.setRoleId(teachersEntity.getRoles().getId());
		}
		return teachers;
	}
	
	/**
	 * Mapping from 'Teachers' to 'TeachersEntity'
	 * @param teachers
	 * @param teachersEntity
	 */
	public void mapTeachersToTeachersEntity(Teachers teachers, TeachersEntity teachersEntity) {
		if(teachers == null) {
			return;
		}

		//--- Generic mapping 
		map(teachers, teachersEntity);

		//--- Link mapping ( link : teachers )
		if( hasLinkToRoles(teachers) ) {
			RolesEntity roles1 = new RolesEntity();
			roles1.setId( teachers.getRoleId() );
			teachersEntity.setRoles( roles1 );
		} else {
			teachersEntity.setRoles( null );
		}

	}
	
	/**
	 * Verify that Roles id is valid.
	 * @param Roles Roles
	 * @return boolean
	 */
	private boolean hasLinkToRoles(Teachers teachers) {
		if(teachers.getRoleId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}