/*
 * Created on 17 May 2016 ( Time 04:14:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.business.service.impl;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import javax.annotation.Resource;

import org.marks.bean.StudentsDisciplineSemestr;
import org.marks.bean.jpa.StudentsDisciplineSemestrEntity;
import org.marks.business.service.StudentsDisciplineSemestrService;
import org.marks.business.service.mapping.StudentsDisciplineSemestrServiceMapper;
import org.marks.persistence.PersistenceServiceProvider;
import org.marks.persistence.services.StudentsDisciplineSemestrPersistence;
import org.springframework.stereotype.Component;

/**
 * Implementation of StudentsDisciplineSemestrService
 */
@Component
public class StudentsDisciplineSemestrServiceImpl implements StudentsDisciplineSemestrService {

	private StudentsDisciplineSemestrPersistence studentsDisciplineSemestrPersistence;

	@Resource
	private StudentsDisciplineSemestrServiceMapper studentsDisciplineSemestrServiceMapper;
	
	public StudentsDisciplineSemestrServiceImpl() {
		studentsDisciplineSemestrPersistence = PersistenceServiceProvider.getService(StudentsDisciplineSemestrPersistence.class);
	}
		
	@Override
	public StudentsDisciplineSemestr findById(Integer id) {
		StudentsDisciplineSemestrEntity entity = studentsDisciplineSemestrPersistence.load(id);
		return studentsDisciplineSemestrServiceMapper.mapStudentsDisciplineSemestrEntityToStudentsDisciplineSemestr(entity);
	}

	@Override
	public List<StudentsDisciplineSemestr> findAll() {
		List<StudentsDisciplineSemestrEntity> entities = studentsDisciplineSemestrPersistence.loadAll();
		List<StudentsDisciplineSemestr> beans = new ArrayList<StudentsDisciplineSemestr>();
		for(StudentsDisciplineSemestrEntity entity : entities) {
			beans.add(studentsDisciplineSemestrServiceMapper.mapStudentsDisciplineSemestrEntityToStudentsDisciplineSemestr(entity));
		}
		return beans;
	}

	@Override
	public StudentsDisciplineSemestr save(StudentsDisciplineSemestr studentsDisciplineSemestr) {
		return update(studentsDisciplineSemestr) ;
	}

	@Override
	public StudentsDisciplineSemestr create(StudentsDisciplineSemestr studentsDisciplineSemestr) {
		if(studentsDisciplineSemestrPersistence.load(studentsDisciplineSemestr.getId()) != null) {
			throw new IllegalStateException("already.exists");
		}
		StudentsDisciplineSemestrEntity studentsDisciplineSemestrEntity = new StudentsDisciplineSemestrEntity();
		studentsDisciplineSemestrServiceMapper.mapStudentsDisciplineSemestrToStudentsDisciplineSemestrEntity(studentsDisciplineSemestr, studentsDisciplineSemestrEntity);
		StudentsDisciplineSemestrEntity studentsDisciplineSemestrEntitySaved = studentsDisciplineSemestrPersistence.save(studentsDisciplineSemestrEntity);
		return studentsDisciplineSemestrServiceMapper.mapStudentsDisciplineSemestrEntityToStudentsDisciplineSemestr(studentsDisciplineSemestrEntitySaved);
	}

	@Override
	public StudentsDisciplineSemestr update(StudentsDisciplineSemestr studentsDisciplineSemestr) {
		StudentsDisciplineSemestrEntity studentsDisciplineSemestrEntity = studentsDisciplineSemestrPersistence.load(studentsDisciplineSemestr.getId());
		studentsDisciplineSemestrServiceMapper.mapStudentsDisciplineSemestrToStudentsDisciplineSemestrEntity(studentsDisciplineSemestr, studentsDisciplineSemestrEntity);
		StudentsDisciplineSemestrEntity studentsDisciplineSemestrEntitySaved = studentsDisciplineSemestrPersistence.save(studentsDisciplineSemestrEntity);
		return studentsDisciplineSemestrServiceMapper.mapStudentsDisciplineSemestrEntityToStudentsDisciplineSemestr(studentsDisciplineSemestrEntitySaved);
	}

	@Override
	public void delete(Integer id) {
		studentsDisciplineSemestrPersistence.delete(id);
	}

	public StudentsDisciplineSemestrPersistence getStudentsDisciplineSemestrPersistence() {
		return studentsDisciplineSemestrPersistence;
	}

	public void setStudentsDisciplineSemestrPersistence(StudentsDisciplineSemestrPersistence studentsDisciplineSemestrPersistence) {
		this.studentsDisciplineSemestrPersistence = studentsDisciplineSemestrPersistence;
	}

	public StudentsDisciplineSemestrServiceMapper getStudentsDisciplineSemestrServiceMapper() {
		return studentsDisciplineSemestrServiceMapper;
	}

	public void setStudentsDisciplineSemestrServiceMapper(StudentsDisciplineSemestrServiceMapper studentsDisciplineSemestrServiceMapper) {
		this.studentsDisciplineSemestrServiceMapper = studentsDisciplineSemestrServiceMapper;
	}

}
