/*
 * Created on 17 May 2016 ( Time 04:14:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.business.service;

import java.util.List;

import org.marks.bean.DisciplineParams;

/**
 * Business Service Interface for entity DisciplineParams.
 */
public interface DisciplineParamsService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	DisciplineParams findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<DisciplineParams> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	DisciplineParams save(DisciplineParams entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	DisciplineParams update(DisciplineParams entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	DisciplineParams create(DisciplineParams entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
