/*
 * Created on 17 May 2016 ( Time 04:14:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.business.service;

import java.util.List;

import org.marks.bean.DisciplinesSemestr;

/**
 * Business Service Interface for entity DisciplinesSemestr.
 */
public interface DisciplinesSemestrService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	DisciplinesSemestr findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<DisciplinesSemestr> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	DisciplinesSemestr save(DisciplinesSemestr entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	DisciplinesSemestr update(DisciplinesSemestr entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	DisciplinesSemestr create(DisciplinesSemestr entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
