/*
 * Created on 17 May 2016 ( Time 04:14:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.business.service;

import java.util.List;

import org.marks.bean.Disciplines;

/**
 * Business Service Interface for entity Disciplines.
 */
public interface DisciplinesService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Disciplines findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Disciplines> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Disciplines save(Disciplines entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Disciplines update(Disciplines entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Disciplines create(Disciplines entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
