/*
 * Created on 17 May 2016 ( Time 04:14:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.business.service;

import java.util.List;

import org.marks.bean.Groups;

/**
 * Business Service Interface for entity Groups.
 */
public interface GroupsService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Groups findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Groups> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Groups save(Groups entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Groups update(Groups entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Groups create(Groups entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
