/*
 * Created on 17 May 2016 ( Time 04:14:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.business.service;

import java.util.List;

import org.marks.bean.Roles;

/**
 * Business Service Interface for entity Roles.
 */
public interface RolesService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Roles findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Roles> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Roles save(Roles entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Roles update(Roles entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Roles create(Roles entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
