/*
 * Created on 17 May 2016 ( Time 04:14:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.business.service;

import java.util.List;

import org.marks.bean.Specialities;

/**
 * Business Service Interface for entity Specialities.
 */
public interface SpecialitiesService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Specialities findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Specialities> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Specialities save(Specialities entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Specialities update(Specialities entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Specialities create(Specialities entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
