/*
 * Created on 17 May 2016 ( Time 04:14:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.business.service;

import java.util.List;

import org.marks.bean.Students;

/**
 * Business Service Interface for entity Students.
 */
public interface StudentsService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Students findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Students> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Students save(Students entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Students update(Students entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Students create(Students entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
