/*
 * Created on 17 May 2016 ( Time 04:14:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.business.service;

import java.util.List;

import org.marks.bean.StudentsDisciplineSemestr;

/**
 * Business Service Interface for entity StudentsDisciplineSemestr.
 */
public interface StudentsDisciplineSemestrService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	StudentsDisciplineSemestr findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<StudentsDisciplineSemestr> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	StudentsDisciplineSemestr save(StudentsDisciplineSemestr entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	StudentsDisciplineSemestr update(StudentsDisciplineSemestr entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	StudentsDisciplineSemestr create(StudentsDisciplineSemestr entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
