/*
 * Created on 17 May 2016 ( Time 04:14:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.business.service;

import java.util.List;

import org.marks.bean.Teachers;

/**
 * Business Service Interface for entity Teachers.
 */
public interface TeachersService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Teachers findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Teachers> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Teachers save(Teachers entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Teachers update(Teachers entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Teachers create(Teachers entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
