/*
 * Created on 17 May 2016 ( Time 04:14:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.marks.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "disciplines"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="disciplines", schema="sheet" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="DisciplinesEntity.countAll", query="SELECT COUNT(x) FROM DisciplinesEntity x" )
} )
public class DisciplinesEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="name", length=2147483647)
    private String     name         ;

    @Column(name="study_plan_code")
    private Integer    studyPlanCode ;

	// "teacherId" (column "teacher_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="teacher_id", referencedColumnName="id")
    private TeachersEntity teachers    ;

    @OneToMany(mappedBy="disciplines", targetEntity=DisciplinesSemestrEntity.class)
    private List<DisciplinesSemestrEntity> listOfDisciplinesSemestr;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public DisciplinesEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : name ( text ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    //--- DATABASE MAPPING : study_plan_code ( int4 ) 
    public void setStudyPlanCode( Integer studyPlanCode ) {
        this.studyPlanCode = studyPlanCode;
    }
    public Integer getStudyPlanCode() {
        return this.studyPlanCode;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTeachers( TeachersEntity teachers ) {
        this.teachers = teachers;
    }
    public TeachersEntity getTeachers() {
        return this.teachers;
    }

    public void setListOfDisciplinesSemestr( List<DisciplinesSemestrEntity> listOfDisciplinesSemestr ) {
        this.listOfDisciplinesSemestr = listOfDisciplinesSemestr;
    }
    public List<DisciplinesSemestrEntity> getListOfDisciplinesSemestr() {
        return this.listOfDisciplinesSemestr;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(name);
        sb.append("|");
        sb.append(studyPlanCode);
        return sb.toString(); 
    } 

}
