/*
 * Created on 17 May 2016 ( Time 04:14:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.marks.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "specialities"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="specialities", schema="sheet" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="SpecialitiesEntity.countAll", query="SELECT COUNT(x) FROM SpecialitiesEntity x" )
} )
public class SpecialitiesEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="speciality_name", length=2147483647)
    private String     specialityName ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="specialities", targetEntity=GroupsEntity.class)
    private List<GroupsEntity> listOfGroups;


    @OneToMany(mappedBy="specialities", targetEntity=DisciplinesSemestrEntity.class)
    private List<DisciplinesSemestrEntity> listOfDisciplinesSemestr;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SpecialitiesEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : speciality_name ( text ) 
    public void setSpecialityName( String specialityName ) {
        this.specialityName = specialityName;
    }
    public String getSpecialityName() {
        return this.specialityName;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfGroups( List<GroupsEntity> listOfGroups ) {
        this.listOfGroups = listOfGroups;
    }
    public List<GroupsEntity> getListOfGroups() {
        return this.listOfGroups;
    }


    public void setListOfDisciplinesSemestr( List<DisciplinesSemestrEntity> listOfDisciplinesSemestr ) {
        this.listOfDisciplinesSemestr = listOfDisciplinesSemestr;
    }
    public List<DisciplinesSemestrEntity> getListOfDisciplinesSemestr() {
        return this.listOfDisciplinesSemestr;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(specialityName);
        return sb.toString(); 
    } 

}
