/*
 * Created on 17 May 2016 ( Time 04:14:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.marks.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "students"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="students", schema="sheet" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="StudentsEntity.countAll", query="SELECT COUNT(x) FROM StudentsEntity x" )
} )
public class StudentsEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="full_name", length=2147483647)
    private String     fullName     ;

    @Column(name="record_book_number")
    private Integer    recordBookNumber ;

    @Temporal(TemporalType.DATE)
    @Column(name="start_year")
    private Date       startYear    ;

    @Temporal(TemporalType.DATE)
    @Column(name="end_year")
    private Date       endYear      ;

	// "groupId" (column "group_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="group_id", referencedColumnName="id")
    private GroupsEntity groups      ;

    @OneToMany(mappedBy="students", targetEntity=StudentsDisciplineSemestrEntity.class)
    private List<StudentsDisciplineSemestrEntity> listOfStudentsDisciplineSemestr;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public StudentsEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : full_name ( text ) 
    public void setFullName( String fullName ) {
        this.fullName = fullName;
    }
    public String getFullName() {
        return this.fullName;
    }

    //--- DATABASE MAPPING : record_book_number ( int4 ) 
    public void setRecordBookNumber( Integer recordBookNumber ) {
        this.recordBookNumber = recordBookNumber;
    }
    public Integer getRecordBookNumber() {
        return this.recordBookNumber;
    }

    //--- DATABASE MAPPING : start_year ( date ) 
    public void setStartYear( Date startYear ) {
        this.startYear = startYear;
    }
    public Date getStartYear() {
        return this.startYear;
    }

    //--- DATABASE MAPPING : end_year ( date ) 
    public void setEndYear( Date endYear ) {
        this.endYear = endYear;
    }
    public Date getEndYear() {
        return this.endYear;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setGroups( GroupsEntity groups ) {
        this.groups = groups;
    }
    public GroupsEntity getGroups() {
        return this.groups;
    }

    public void setListOfStudentsDisciplineSemestr( List<StudentsDisciplineSemestrEntity> listOfStudentsDisciplineSemestr ) {
        this.listOfStudentsDisciplineSemestr = listOfStudentsDisciplineSemestr;
    }
    public List<StudentsDisciplineSemestrEntity> getListOfStudentsDisciplineSemestr() {
        return this.listOfStudentsDisciplineSemestr;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(fullName);
        sb.append("|");
        sb.append(recordBookNumber);
        sb.append("|");
        sb.append(startYear);
        sb.append("|");
        sb.append(endYear);
        return sb.toString(); 
    } 

}
