/*
 * Created on 17 May 2016 ( Time 04:14:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.marks.bean.DisciplineParams;
import org.marks.business.service.DisciplineParamsService;
import org.marks.web.listitem.DisciplineParamsListItem;

/**
 * Spring MVC controller for 'DisciplineParams' management.
 */
@Controller
public class DisciplineParamsRestController {

	@Resource
	private DisciplineParamsService disciplineParamsService;
	
	@RequestMapping( value="/items/disciplineParams",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<DisciplineParamsListItem> findAllAsListItems() {
		List<DisciplineParams> list = disciplineParamsService.findAll();
		List<DisciplineParamsListItem> items = new LinkedList<DisciplineParamsListItem>();
		for ( DisciplineParams disciplineParams : list ) {
			items.add(new DisciplineParamsListItem( disciplineParams ) );
		}
		return items;
	}
	
	@RequestMapping( value="/disciplineParams",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<DisciplineParams> findAll() {
		return disciplineParamsService.findAll();
	}

	@RequestMapping( value="/disciplineParams/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public DisciplineParams findOne(@PathVariable("id") Integer id) {
		return disciplineParamsService.findById(id);
	}
	
	@RequestMapping( value="/disciplineParams",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public DisciplineParams create(@RequestBody DisciplineParams disciplineParams) {
		return disciplineParamsService.create(disciplineParams);
	}

	@RequestMapping( value="/disciplineParams/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public DisciplineParams update(@PathVariable("id") Integer id, @RequestBody DisciplineParams disciplineParams) {
		return disciplineParamsService.update(disciplineParams);
	}

	@RequestMapping( value="/disciplineParams/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		disciplineParamsService.delete(id);
	}
	
}
