/*
 * Created on 17 May 2016 ( Time 04:14:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class DisciplineParams implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer disciplineSemestrId;

    @Size( max = 2147483647 )
    private String activityName;


    private Integer activityMaxQuantity;


    private Integer scorePerActivity;


    private Integer scoreMax;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDisciplineSemestrId( Integer disciplineSemestrId ) {
        this.disciplineSemestrId = disciplineSemestrId;
    }
    public Integer getDisciplineSemestrId() {
        return this.disciplineSemestrId;
    }

    public void setActivityName( String activityName ) {
        this.activityName = activityName;
    }
    public String getActivityName() {
        return this.activityName;
    }

    public void setActivityMaxQuantity( Integer activityMaxQuantity ) {
        this.activityMaxQuantity = activityMaxQuantity;
    }
    public Integer getActivityMaxQuantity() {
        return this.activityMaxQuantity;
    }

    public void setScorePerActivity( Integer scorePerActivity ) {
        this.scorePerActivity = scorePerActivity;
    }
    public Integer getScorePerActivity() {
        return this.scorePerActivity;
    }

    public void setScoreMax( Integer scoreMax ) {
        this.scoreMax = scoreMax;
    }
    public Integer getScoreMax() {
        return this.scoreMax;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(disciplineSemestrId);
        sb.append("|");
        sb.append(activityName);
        sb.append("|");
        sb.append(activityMaxQuantity);
        sb.append("|");
        sb.append(scorePerActivity);
        sb.append("|");
        sb.append(scoreMax);
        return sb.toString(); 
    } 


}
