/*
 * Created on 17 May 2016 ( Time 04:14:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class DisciplinesSemestr implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer disciplineId;


    private Integer specialityId;


    private Integer semestr;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDisciplineId( Integer disciplineId ) {
        this.disciplineId = disciplineId;
    }
    public Integer getDisciplineId() {
        return this.disciplineId;
    }

    public void setSpecialityId( Integer specialityId ) {
        this.specialityId = specialityId;
    }
    public Integer getSpecialityId() {
        return this.specialityId;
    }

    public void setSemestr( Integer semestr ) {
        this.semestr = semestr;
    }
    public Integer getSemestr() {
        return this.semestr;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(disciplineId);
        sb.append("|");
        sb.append(specialityId);
        sb.append("|");
        sb.append(semestr);
        return sb.toString(); 
    } 


}
