/*
 * Created on 17 May 2016 ( Time 04:14:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Groups implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer specialityId;


    private Integer course;


    private Integer groupNumber;

    @Size( max = 80 )
    private String faculty;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setSpecialityId( Integer specialityId ) {
        this.specialityId = specialityId;
    }
    public Integer getSpecialityId() {
        return this.specialityId;
    }

    public void setCourse( Integer course ) {
        this.course = course;
    }
    public Integer getCourse() {
        return this.course;
    }

    public void setGroupNumber( Integer groupNumber ) {
        this.groupNumber = groupNumber;
    }
    public Integer getGroupNumber() {
        return this.groupNumber;
    }

    public void setFaculty( String faculty ) {
        this.faculty = faculty;
    }
    public String getFaculty() {
        return this.faculty;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(specialityId);
        sb.append("|");
        sb.append(course);
        sb.append("|");
        sb.append(groupNumber);
        sb.append("|");
        sb.append(faculty);
        return sb.toString(); 
    } 


}
