/*
 * Created on 17 May 2016 ( Time 04:14:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class StudentsDisciplineSemestr implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer studentId;


    private Integer disciplineParamId;


    private Integer studentScore;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setStudentId( Integer studentId ) {
        this.studentId = studentId;
    }
    public Integer getStudentId() {
        return this.studentId;
    }

    public void setDisciplineParamId( Integer disciplineParamId ) {
        this.disciplineParamId = disciplineParamId;
    }
    public Integer getDisciplineParamId() {
        return this.disciplineParamId;
    }

    public void setStudentScore( Integer studentScore ) {
        this.studentScore = studentScore;
    }
    public Integer getStudentScore() {
        return this.studentScore;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(studentId);
        sb.append("|");
        sb.append(disciplineParamId);
        sb.append("|");
        sb.append(studentScore);
        return sb.toString(); 
    } 


}
