/*
 * Created on 17 May 2016 ( Time 04:14:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Teachers implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 2147483647 )
    private String fullName;

    @Size( max = 50 )
    private String login;

    @Size( max = 50 )
    private String password;

    @Size( max = 50 )
    private String cathedra;


    private Integer roleId;

    @Size( max = 2147483647 )
    private String enabled;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setFullName( String fullName ) {
        this.fullName = fullName;
    }
    public String getFullName() {
        return this.fullName;
    }

    public void setLogin( String login ) {
        this.login = login;
    }
    public String getLogin() {
        return this.login;
    }

    public void setPassword( String password ) {
        this.password = password;
    }
    public String getPassword() {
        return this.password;
    }

    public void setCathedra( String cathedra ) {
        this.cathedra = cathedra;
    }
    public String getCathedra() {
        return this.cathedra;
    }

    public void setRoleId( Integer roleId ) {
        this.roleId = roleId;
    }
    public Integer getRoleId() {
        return this.roleId;
    }

    public void setEnabled( String enabled ) {
        this.enabled = enabled;
    }
    public String getEnabled() {
        return this.enabled;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(fullName);
        sb.append("|");
        sb.append(login);
        sb.append("|");
        sb.append(password);
        sb.append("|");
        sb.append(cathedra);
        sb.append("|");
        sb.append(roleId);
        sb.append("|");
        sb.append(enabled);
        return sb.toString(); 
    } 


}
