/*
 * Created on 17 May 2016 ( Time 04:14:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.marks.web.common.AbstractController;
import org.marks.web.common.FormMode;
import org.marks.web.common.Message;
import org.marks.web.common.MessageType;

//--- Entities
import org.marks.bean.DisciplinesSemestr;
import org.marks.bean.Disciplines;
import org.marks.bean.Specialities;

//--- Services 
import org.marks.business.service.DisciplinesSemestrService;
import org.marks.business.service.DisciplinesService;
import org.marks.business.service.SpecialitiesService;

//--- List Items 
import org.marks.web.listitem.DisciplinesListItem;
import org.marks.web.listitem.SpecialitiesListItem;

/**
 * Spring MVC controller for 'DisciplinesSemestr' management.
 */
@Controller
@RequestMapping("/disciplinesSemestr")
public class DisciplinesSemestrController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "disciplinesSemestr";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "disciplinesSemestr/form";
	private static final String JSP_LIST   = "disciplinesSemestr/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/disciplinesSemestr/create";
	private static final String SAVE_ACTION_UPDATE   = "/disciplinesSemestr/update";

	//--- Main entity service
	@Resource
    private DisciplinesSemestrService disciplinesSemestrService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private DisciplinesService disciplinesService; // Injected by Spring
	@Resource
    private SpecialitiesService specialitiesService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public DisciplinesSemestrController() {
		super(DisciplinesSemestrController.class, MAIN_ENTITY_NAME );
		log("DisciplinesSemestrController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "Disciplines"
	 * @param model
	 */
	private void populateListOfDisciplinesItems(Model model) {
		List<Disciplines> list = disciplinesService.findAll();
		List<DisciplinesListItem> items = new LinkedList<DisciplinesListItem>();
		for ( Disciplines disciplines : list ) {
			items.add(new DisciplinesListItem( disciplines ) );
		}
		model.addAttribute("listOfDisciplinesItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "Specialities"
	 * @param model
	 */
	private void populateListOfSpecialitiesItems(Model model) {
		List<Specialities> list = specialitiesService.findAll();
		List<SpecialitiesListItem> items = new LinkedList<SpecialitiesListItem>();
		for ( Specialities specialities : list ) {
			items.add(new SpecialitiesListItem( specialities ) );
		}
		model.addAttribute("listOfSpecialitiesItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param disciplinesSemestr
	 */
	private void populateModel(Model model, DisciplinesSemestr disciplinesSemestr, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, disciplinesSemestr);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfDisciplinesItems(model);
			populateListOfSpecialitiesItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfDisciplinesItems(model);
			populateListOfSpecialitiesItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of DisciplinesSemestr found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<DisciplinesSemestr> list = disciplinesSemestrService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new DisciplinesSemestr
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		DisciplinesSemestr disciplinesSemestr = new DisciplinesSemestr();	
		populateModel( model, disciplinesSemestr, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing DisciplinesSemestr
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{id}")
	public String formForUpdate(Model model, @PathVariable("id") Integer id ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		DisciplinesSemestr disciplinesSemestr = disciplinesSemestrService.findById(id);
		populateModel( model, disciplinesSemestr, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param disciplinesSemestr  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid DisciplinesSemestr disciplinesSemestr, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				DisciplinesSemestr disciplinesSemestrCreated = disciplinesSemestrService.create(disciplinesSemestr); 
				model.addAttribute(MAIN_ENTITY_NAME, disciplinesSemestrCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, disciplinesSemestr.getId() );
			} else {
				populateModel( model, disciplinesSemestr, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "disciplinesSemestr.error.create", e);
			populateModel( model, disciplinesSemestr, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param disciplinesSemestr  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid DisciplinesSemestr disciplinesSemestr, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				DisciplinesSemestr disciplinesSemestrSaved = disciplinesSemestrService.update(disciplinesSemestr);
				model.addAttribute(MAIN_ENTITY_NAME, disciplinesSemestrSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, disciplinesSemestr.getId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, disciplinesSemestr, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "disciplinesSemestr.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, disciplinesSemestr, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{id}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("id") Integer id) {
		log("Action 'delete'" );
		try {
			disciplinesSemestrService.delete( id );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "disciplinesSemestr.error.delete", e);
		}
		return redirectToList();
	}

}
