/*
 * Created on 17 May 2016 ( Time 04:14:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.marks.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.marks.web.common.AbstractController;
import org.marks.web.common.FormMode;
import org.marks.web.common.Message;
import org.marks.web.common.MessageType;

//--- Entities
import org.marks.bean.StudentsDisciplineSemestr;
import org.marks.bean.DisciplineParams;
import org.marks.bean.Students;

//--- Services 
import org.marks.business.service.StudentsDisciplineSemestrService;
import org.marks.business.service.DisciplineParamsService;
import org.marks.business.service.StudentsService;

//--- List Items 
import org.marks.web.listitem.DisciplineParamsListItem;
import org.marks.web.listitem.StudentsListItem;

/**
 * Spring MVC controller for 'StudentsDisciplineSemestr' management.
 */
@Controller
@RequestMapping("/studentsDisciplineSemestr")
public class StudentsDisciplineSemestrController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "studentsDisciplineSemestr";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "studentsDisciplineSemestr/form";
	private static final String JSP_LIST   = "studentsDisciplineSemestr/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/studentsDisciplineSemestr/create";
	private static final String SAVE_ACTION_UPDATE   = "/studentsDisciplineSemestr/update";

	//--- Main entity service
	@Resource
    private StudentsDisciplineSemestrService studentsDisciplineSemestrService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private DisciplineParamsService disciplineParamsService; // Injected by Spring
	@Resource
    private StudentsService studentsService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public StudentsDisciplineSemestrController() {
		super(StudentsDisciplineSemestrController.class, MAIN_ENTITY_NAME );
		log("StudentsDisciplineSemestrController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "DisciplineParams"
	 * @param model
	 */
	private void populateListOfDisciplineParamsItems(Model model) {
		List<DisciplineParams> list = disciplineParamsService.findAll();
		List<DisciplineParamsListItem> items = new LinkedList<DisciplineParamsListItem>();
		for ( DisciplineParams disciplineParams : list ) {
			items.add(new DisciplineParamsListItem( disciplineParams ) );
		}
		model.addAttribute("listOfDisciplineParamsItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "Students"
	 * @param model
	 */
	private void populateListOfStudentsItems(Model model) {
		List<Students> list = studentsService.findAll();
		List<StudentsListItem> items = new LinkedList<StudentsListItem>();
		for ( Students students : list ) {
			items.add(new StudentsListItem( students ) );
		}
		model.addAttribute("listOfStudentsItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param studentsDisciplineSemestr
	 */
	private void populateModel(Model model, StudentsDisciplineSemestr studentsDisciplineSemestr, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, studentsDisciplineSemestr);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfDisciplineParamsItems(model);
			populateListOfStudentsItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfStudentsItems(model);
			populateListOfDisciplineParamsItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of StudentsDisciplineSemestr found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<StudentsDisciplineSemestr> list = studentsDisciplineSemestrService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new StudentsDisciplineSemestr
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		StudentsDisciplineSemestr studentsDisciplineSemestr = new StudentsDisciplineSemestr();	
		populateModel( model, studentsDisciplineSemestr, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing StudentsDisciplineSemestr
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{id}")
	public String formForUpdate(Model model, @PathVariable("id") Integer id ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		StudentsDisciplineSemestr studentsDisciplineSemestr = studentsDisciplineSemestrService.findById(id);
		populateModel( model, studentsDisciplineSemestr, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param studentsDisciplineSemestr  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid StudentsDisciplineSemestr studentsDisciplineSemestr, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				StudentsDisciplineSemestr studentsDisciplineSemestrCreated = studentsDisciplineSemestrService.create(studentsDisciplineSemestr); 
				model.addAttribute(MAIN_ENTITY_NAME, studentsDisciplineSemestrCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, studentsDisciplineSemestr.getId() );
			} else {
				populateModel( model, studentsDisciplineSemestr, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "studentsDisciplineSemestr.error.create", e);
			populateModel( model, studentsDisciplineSemestr, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param studentsDisciplineSemestr  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid StudentsDisciplineSemestr studentsDisciplineSemestr, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				StudentsDisciplineSemestr studentsDisciplineSemestrSaved = studentsDisciplineSemestrService.update(studentsDisciplineSemestr);
				model.addAttribute(MAIN_ENTITY_NAME, studentsDisciplineSemestrSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, studentsDisciplineSemestr.getId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, studentsDisciplineSemestr, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "studentsDisciplineSemestr.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, studentsDisciplineSemestr, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{id}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("id") Integer id) {
		log("Action 'delete'" );
		try {
			studentsDisciplineSemestrService.delete( id );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "studentsDisciplineSemestr.error.delete", e);
		}
		return redirectToList();
	}

}
